### ISSUE TITLE
[TASK] Implement unimplemented protocol-substrate proposals 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/protocol-substrate#164]
# Overview 

Implement the missing proposals in `protocol-substrate`, including the following: 

- [x] [FeeRecipientUpdateProposal](https://docs.rs/webb-proposals/latest/webb_proposals/evm/struct.FeeRecipientUpdateProposal.html)
- [x] [MaxDepositLimitProposal](https://docs.rs/webb-proposals/latest/webb_proposals/evm/struct.MaxDepositLimitProposal.html)
- [x] [MinWithdrawalLimitProposal](https://docs.rs/webb-proposals/latest/webb_proposals/evm/struct.MinWithdrawalLimitProposal.html)
- [x] [RescueTokensProposal](https://docs.rs/webb-proposals/latest/webb_proposals/evm/struct.RescueTokensProposal.html)
- [ ] [SetTreasuryHandlerProposal](https://docs.rs/webb-proposals/latest/webb_proposals/evm/struct.SetTreasuryHandlerProposal.html)

**Proposals Implemented:**

- [x] [AnchorUpdateProposal](https://docs.rs/webb-proposals/latest/webb_proposals/substrate/struct.AnchorUpdateProposal.html)
- [x] [ResourceIdUpdateProposal](https://docs.rs/webb-proposals/latest/webb_proposals/substrate/struct.ResourceIdUpdateProposal.html)
- [x] [TokenAddProposal](https://docs.rs/webb-proposals/latest/webb_proposals/substrate/struct.TokenAddProposal.html)	
- [x] [TokenRemoveProposal](https://docs.rs/webb-proposals/latest/webb_proposals/substrate/struct.TokenRemoveProposal.html)	
- [x] [WrappingFeeUpdateProposal](https://docs.rs/webb-proposals/latest/webb_proposals/substrate/struct.WrappingFeeUpdateProposal.html)

### General implementation details

- Add proposal logic in the appropriate handler (e.g. anchor-handler, token-wrapper-handler etc)
- Add test to `tests_signature_bridge.rs`

**Comment by dutterbutter** [comment]
Related spec: https://github.com/webb-tools/protocol-substrate/issues/142

**Comment by salman01zp** [comment]
@drewstone  do we need a treasury handling proposals since we are using `pallet_treasury`

**Comment by salman01zp** [comment]
also need input on how to handle proposal nonce for `set_fee_recipient` since `ProposalNonce` is a storage map  of type (pool_name , nonce)  [here](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/token-wrapper/src/lib.rs#L149)
can we have it as just `StorageValue` ? wdyt @drewstone 
```rust
pub type ProposalNonce<T: Config> = StorageMap<_, Blake2_128Concat, Vec<u8>, T::ProposalNonce>;
```
