### ISSUE TITLE
Change set_resource function on the signature-bridge pallet

### ISSUE THREAD

**Issue by saiakilesh** [webb-tools/protocol-substrate#165]
I think we might want to change the `set_resource` function https://github.com/webb-tools/protocol-substrate/blob/main/pallets/signature-bridge/src/lib.rs#L244 on the `signature-bridge` pallet a bit. Right now in our tests, the root/admin calls the `set_resource` function. But what we really want is the `set_resource` function to be a proposal which is executed through the `signature-bridge`.

It is a little bit tricky how to do this because the register `r_id` proposal does not follow the usual `signature-bridge -> handler function` pattern, but here is one idea:

To execute the `set_resource` function we can still go through the `execute_proposal` function and the proposal data can still be `(r_id, zeroes, nonce, call)` with the `call` corresponding to the `set_resource` function. Then, in the `set_resource` function we can ensure that the origin is the `signature-bridge`. 

One caveat is I'm not sure if it is possible to check that the origin of a call is the same as the pallet that the call is defined in.

**Comment by drewstone** [comment]
I think we should leave the `set_resource` ID as it's an additional governance route that the chain's democracy or root system can use but we should just add a similar function as we have on the Solidity protocol where we set a new resourceID with the DKG signature (or the `T::SignatureVerifier` system)
