### ISSUE TITLE
[SPEC] Set ResourceId with Signature

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/protocol-substrate#219]
# Overview 

Currently, we don't have `set_resource_with_signature` on the signature bridge pallet as we have on solidity [here](https://github.com/webb-tools/protocol-solidity/blob/main/contracts/SignatureBridge.sol#L49-L79) . 

Also, the current implementation on the signature bridge pallet does not allow one to  update `Resource` and `AnchorList` storage
without passing through the `bridge_origin` check. 

So the idea is to have the `set_resource_with_signature` function in pallet, which will process the `ResourceIdUpdateProposal` and dispatch a call to  the`anchor-handler-pallet` which will update the Resource storage.

## Flow 

Step1 : `set_resource_with_signature` function which will be similar to executeProposal except it wont have any Resource validation check 
```rust
#[pallet::weight(195_000_000)]
pub fn set_resource_with_signature(
	origin: OriginFor<T>,
	src_id: T::ChainId,
	call: Box<<T as Config<I>>::Proposal>,
	proposal_data: Vec<u8>,
	signature: Vec<u8>,
) -> DispatchResultWithPostInfo {
	let _ = ensure_signed(origin)?;
	let r_id = Self::parse_r_id_from_proposal_data(&proposal_data)?;
	let nonce = Self::parse_nonce_from_proposal_data(&proposal_data)?;
	let parsed_call = Self::parse_call_from_proposal_data(&proposal_data);

	// Nonce should be greater than the proposal nonce in storage
	let proposal_nonce = ProposalNonce::<T, I>::get();
	ensure!(proposal_nonce < nonce, Error::<T, I>::InvalidNonce);

	// Nonce should increment by 1
	ensure!(
		nonce <= proposal_nonce + T::ProposalNonce::from(1u32),
		Error::<T, I>::InvalidNonce
	);

	ensure!(
		T::SignatureVerifier::verify(&Self::maintainer(), &proposal_data[..], &signature)
			.unwrap_or(false),
		Error::<T, I>::InvalidPermissions,
	);
	
	// Ensure that call is consistent with parsed_call
	let encoded_call = call.encode();
	ensure!(encoded_call == parsed_call, Error::<T, I>::CallNotConsistentWithProposalData);

	// Ensure this chain id matches the r_id
	let execution_chain_id_type = Self::parse_chain_id_type_from_r_id(r_id);
	let this_chain_id_type =
		compute_chain_id_type(T::ChainIdentifier::get(), T::ChainType::get());

	ensure!(
		this_chain_id_type == execution_chain_id_type,
		Error::<T, I>::IncorrectExecutionChainIdType
	);

	Self::finalize_execution(src_id, nonce, call)
}
```

Step2: Create `execute_set_resource_proposal` function in `anchor-handler-pallet`. Which will add the `Resource` and update `AnchorList`.
```rust

/// This will by called by bridge when proposal to set new resource for
/// handler has been successfully voted on
#[pallet::weight(195_000_000)]
pub fn execute_set_resource_proposal(
	origin: OriginFor<T>,
	r_id: ResourceId,
	tree_id: T::TreeId
) -> DispatchResultWithPostInfo {
	T::BridgeOrigin::ensure_origin(origin)?;
	self::set_resource(proposal_data, tree_id)
}


fn set_resource(
        r_id: ResourceId,
        tree_id: T::TreeId
) -> DispatchResultWithPostInfo {
        resource_id
        ensure!(!AnchorList::<T, I>::contains_key(r_id), Error::<T, I>::ResourceIsAlreadyAnchored);
	        AnchorList::<T, I>::insert(r_id, tree_id);
        Counts::<T, I>::insert(src_chain_id, 0);
        Self::deposit_event(Event::ResourceAnchored);
        Ok(().into())
	}
```
# Task Checklist
- [ ] Implement `ResourceIdUpdateProposal` for substrate, similar to solidity [here](https://github.com/webb-tools/webb-rs/blob/main/proposals/src/proposal/evm/resource_id_update.rs)
- [ ] Implement `set_resource_with_signature`  in  signature-bridge-pallet

# Questions/Issues

**Comment by dutterbutter** [comment]
Closed in https://github.com/webb-tools/protocol-substrate/pull/222

**Comment by dutterbutter** [comment]
Closed in https://github.com/webb-tools/protocol-substrate/pull/222
