### ISSUE TITLE
[CHECKLIST] Tracking issue for failing benchmarks

### ISSUE THREAD

**Issue by 1xstj** [webb-tools/protocol-substrate#227]
# Overview

Tracking issue for failing/outdated benchmarks in repo

How to reproduce
Run `cargo b --features runtime-benchmarks` from base directory

## Checklist
- [X] Anchor
- [x] Hasher
- [x] Mixer
- [x] Mt
- [x] verifier
- [ ] VAnchor

**Comment by dutterbutter** [comment]
@1xstj is the vanchor benchmarks still not completed?

**Comment by dutterbutter** [comment]
ping @1xstj
