### ISSUE TITLE
Unable to use vAnchor deployments done in genesis

### ISSUE THREAD

**Issue by nepoche** [webb-tools/protocol-substrate#245]
**Issue summary**
When attempting to interact with the vAnchor deployments in the dApp, I am unable to make deposits due to `-linkableTreeBn254.InvalidMerkleRoots rejected`.  

**Other information and links**

It appears to be related to the maxEdges set on the anchors created in genesis (2 instead of 1). This is the result of `api.query.linkableTreeBn254.maxEdges`

```
linkableTreeBn254.maxEdges: u32
[
  [
    [
      6
    ]
    1
  ]
  [
    [
      5
    ]
    2
  ]
]
```

**Comment by drewstone** [comment]
Can you push a fix to the chain spec or do you need me to @nepoche ?
