### ISSUE TITLE
Depreciation warnings

### ISSUE THREAD

**Issue by Nutomic** [webb-tools/protocol-substrate#286]
**Issue summary**

There are a lot of deprecation warnings in the code which make the output extremely noisy. They should probably be fixed.

```
warning: use of deprecated struct `pallet::warnings::swap`:
Implicit call indices are deprecated in favour of explicit ones.
Please ensure that all calls have the `pallet::call_index` attribute or that the
`dev-mode` of the pallet is enabled. For more info see:
<https://github.com/paritytech/substrate/pull/12891> and
<https://github.com/paritytech/substrate/pull/11381>.
--> pallets/anonymity-mining/src/lib.rs:168:10
|
168 |         pub fn swap(
|                ^^^^
|
= note: `#[warn(deprecated)]` on by default
```
**Other information and links**

I think this was introduced by https://github.com/webb-tools/protocol-substrate/pull/282

**Comment by drewstone** [comment]
Yep, from the last update. @1xstj if you can include these in your next PRs they're useful for reducing warnings.
