### ISSUE TITLE
[TASK] Update set maintainer to take nonce as input 

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/protocol-substrate#301]
## Overview

The current `set_maintainer` method is outdated it expects DKG to sign a message= (nonce+new_dkg_key) and then it extracts nonce and dkg_key from the message and validates. Check [here](https://github.com/webb-tools/protocol-substrate/blob/main/pallets/signature-bridge/src/lib.rs#L253) for more details
```rust
// nonce should be the first 4 bytes of this message
let nonce_from_maintainer = T::MaintainerNonce::decode(&mut &message[..4])
	.map_err(|_| Error::<T, I>::InvalidNonce)?;
```
## Solution
We need to update this method to take nonce as input which will be provided by the relayer and then validate it.

```rust
pub fn set_maintainer(
  origin: OriginFor<T>,
  nonce: u32,
  message: BoundedVec<u8, T::MaxStringLength>,
  signature: BoundedVec<u8, T::MaxStringLength>,
) {
  let maintainer_nonce = MaintainerNonce::<T, I>::get() + 1u32;
  // Nonce should increment by 1
  ensure!(maintainer_nonce == nonce, Error::<T, I>::InvalidNonce);
}
```

-----
### Task Checklist 

- [ ] Update `set_mainatiner`
- [ ] Update tests

**Comment by drewstone** [comment]
Can you explain more what's wrong with current implementation? Set maintainer is our version of setting governor on Substrate. Are we not meant to verify the nonce from the signed message?

**Comment by salman01zp** [comment]
I will be closing this.. 
Relayer was sending just `dkg_key` as msg to this extrinsic, I will be updating it to send it along with nonce (`msg = nonce+dkg_key`)
