### ISSUE TITLE
[TASK] Fix CI to publish types and publish the package on npm

### ISSUE THREAD

**Issue by shekohex** [webb-tools/protocol-substrate#311]
**Task summary**
Currently the flow for updating the types and publishing them to the NPM is broken.

**Specification reference**
- First appeared in #308 
- First attempt to fix it #309 
- Second attempt #310 

**Other information and links**

Looks like the script is very old and it is very similar to the one used by webb.js to publish new versions to NPM, would be useful if we can update this and fix it ASAP.

**Comment by Nutomic** [comment]
I looked through docs and examples, tried to make some changes but nothing helped. So I opened an issue, hopefully we can get some help that way.

https://github.com/polkadot-js/api/issues/5582
