### ISSUE TITLE
[TASK] Add rpc api for is_known_root method

### ISSUE THREAD

**Issue by salman01zp** [webb-tools/protocol-substrate#325]
## Summary

Add RPC api to validate if the given root is a known root, this will be used by the relayer to validate leaves before caching.

https://github.com/webb-tools/protocol-substrate/blob/main/pallets/mt/src/lib.rs#L492-#L509

```rust
#[method(name = "mt_isKnownRoot")]
fn is_known_root(
	&self,
	tree_id: u32,
	target_root: Element,
	at: Option<BlockHash>,
) -> RpcResult<bool>;



```

**Comment by shekohex** [comment]
This Like a two part operation here.

**Runtime API**:
So for you to do this, you need to declare it for the runtime API first like here:

https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/mt/rpc/runtime-api/src/lib.rs#L5-L10

And then you will need to implement that Runtime API in the `*/runtime/lib.rs` like so:
https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/standalone/runtime/src/lib.rs#L1743-L1752

**RPC:**
And here for the RPC
https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/mt/rpc/src/lib.rs#L32-L51

Then you just implement it inside the RPC

> This an example implementation of the `get_leaves`

https://github.com/webb-tools/protocol-substrate/blob/f0c637dc00625f65a7df28acd2d5f463c5f833c3/pallets/mt/rpc/src/lib.rs#L75-L94

And that's it actually.
