### ISSUE TITLE
Bug: Mixers balances issue

### ISSUE THREAD

**Issue by filiplazovic** [webb-tools/protocol-substrate#73]
# Problem Description

Failed to get a deposit to work on native/non-native assets

# Recreation Steps

- From a custom asset
    - Create a custom asset with a minimum balance of `5` units,and id `5`
    - Mint tokens for an account (say 500 units)
    - Create a mixer for this asset with balances that is less and more than the minimum balance of the currency
    - Try to deposit on those sizes
    - There will be an error `token.BalanceTooLow`
- For native asset id `0`
    - Transfer some balance to an account say (100K)
    - Create Mixer using Charlie with the amount of 5 and asset is native id `0`
    - Try to deposit using an account with enough balance 100k units, or Charlie 8.9KK units
    - Error ⇒ balances.ExistentialDeposit

# Triage

- Existential deposits or Minimum balance?

**Comment by AhmedKorim** [comment]
This was fixed
